### ISSUE TITLE
"Error: not found" when triggering workflow in another repo

### ISSUE THREAD

**Issue by cjyar** [benc-uk/workflow-dispatch#19]
Repo `org/A` has this:
```yaml
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: CI
        token: ${{ secrets.WORKFLOW_PAT }}
        inputs: '{ "blah": "foo", "blurf": "bar" }'
        repo: org/B
```
When the workflow runs, I get this output:
```
Workflow id is: 4336344
Error: Not Found
```
