### ISSUE TITLE
Error: Unable to find workflow in example/repo 😥

### ISSUE THREAD

**Issue by rutgerth1508** [benc-uk/workflow-dispatch#21]
I am getting an error trying to run a different workflow from the current one.
This is the step in the workflow:
```
 - name: Invoke unit test workflow
   uses: benc-uk/workflow-dispatch@v1
   with:
     workflow: Unittests
     token: ${{ secrets.ACCESS_TOKEN }}          
```
And this the Unittests workflow meta data:

```
name: Unittests
on: [workflow_dispatch]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
       ...
```
But when I try and run the first workflow I'll get the following output:
```
Run benc-uk/workflow-dispatch@v1
  with:
    workflow: Unittests
    token: ***
Error: Unable to find workflow 'Unittests' in example/repo 😥
```
Does anyone know a solution for this problem?

**Comment by JayyTurakhia** [comment]
Can you please confirm if the workflow file containing Unittests is on master/main/default branch of the repo.
Refer - [https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run](url)

**Comment by ipeshev** [comment]
Same here , occurred after failed runs in PR branch, but the workflow is in tact in default branch.

**Comment by perezzini** [comment]
Hi! Same problem, here.

**Comment by asafwat** [comment]
i had the same issue, after checking this comment 

https://github.com/benc-uk/workflow-dispatch/issues/1#issuecomment-657763660

it turn out that for some reason the workflow name started with a small letter when i queried github api, although the name started with a capital letter in my workflow file, so i deleted the workflow from master and add it back again and this time i got the correct name from github api and the invoke action worked.

worth to check, it could be the case.

**Comment by santunioni** [comment]
Using the filename is a more stable solution. Can you change in your side?
Example:
```yaml
 - name: Invoke unit test workflow
   uses: benc-uk/workflow-dispatch@v1
   with:
     workflow: unittests.yaml
     token: ${{ secrets.ACCESS_TOKEN }}     
```
