### ISSUE TITLE
Readme for `inputs` not correct?

### ISSUE THREAD

**Issue by CWSites** [benc-uk/workflow-dispatch#23]
I am passing through `inputs` as shown in the example and I'm getting parsing errors in my workflow that it's triggering. I've tried wrapping the `inputs` with a single and double quote, neither work.

## workflow step
```yml
    steps:
      - name: Trigger Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          inputs: "{ 'ref': '${{ github.ref }}', 'sha': '${{ github.sha }}' }"
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow: Deploy to GitHub Pages
```

## failure error
```
  with:
    inputs: { 'ref': 'refs/heads/master', 'sha': 'a6d88433859c590b163bbf77241fe1a74576b3f9' }
    token: ***
    workflow: Deploy to GitHub Pages
Error: Unexpected token ' in JSON at position 2
```

**Comment by CWSites** [comment]
**Update: ** I believe what is going on here is the workflow which is being triggered MUST specify any inputs that are being passed in. If the inputs are specified then the workflow will fail as the input is unexpected.

I updated the workflow which is being triggered with the following

```yml
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'GitHub REF to be used for checkout'
        required: true
      sha:
        description: 'GitHub SHA to be used for checkout'
        required: true
```
