### ISSUE TITLE
not working with delivery bot deployment status

### ISSUE THREAD

**Issue by dreinhardt-terminus** [benc-uk/workflow-dispatch#34]
I trigger a workflow like below:
```yaml
- name: Deploy
  uses: benc-uk/workflow-dispatch@v1
  with:
    workflow: Deploy
    token: ${{ secrets.pull_access_token }}
    repo: org/repo
    ref: master
    inputs: '{"environment": "all"}'
```

And have this step in the workflow that gets triggered by the above workflow:
```yaml
- name: Deployment Pending
  uses: deliverybot/deployment-status@v1
  with:
    state: pending
    token: ${{ github.token }}
```

It seems to trigger just fine but I'm getting the below error:
![image](https://user-images.githubusercontent.com/85892019/150835998-0bb7b902-f441-478a-9210-37ae7c0036e3.png)

If I remove that steps it runs just fine, is there an input I need that I'm just not setting? I checked and the github.token is not empty
