### ISSUE TITLE
Sequential action calls do not wait for completion

### ISSUE THREAD

**Issue by bakoontz2** [benc-uk/workflow-dispatch#39]
Per the documentation:

> This allows you to chain workflows, the classic use case is have a CI build workflow, trigger a CD release/deploy workflow when it completes. Allowing you to maintain separate workflows for CI and CD, and pass data between them as required.

However, an invocation does not appear to wait until the next invocation is triggered.  So it's not clear how this is supposed to work.  For instance:

```
name: Test

on:
  workflow_dispatch

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build common
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Build and deploy common"
          token: ${{ secrets.PAT }}
          repo: name/repo
          ref: master

      - name: Build search
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Build search"
          token: ${{ secrets.PAT }}
          repo: name/repo
          ref: master

      - name: Deploy search
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Deploy search"
          token: ${{ secrets.PAT }}
          repo: name/repo
          ref: master
```

All three steps are executed.  There is no "waiting" between steps.  Did I miss something?

**Comment by benc-uk** [comment]
This is the nature of how the `workflow_dispatch` event works, it's asynchronous. This is probably not the best way to structure a workflow with every step in separate locations. Perhaps this is what you are looking for https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by bakoontz2** [comment]
Here's an example of how one might check for the results:

```     
        - name: Build common
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Build and deploy common"
          token: ${{ secrets.PAT }}
          repo: name/repo
          ref: master

     - uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build-common
        with:
          token: ${{ secrets.PAT }}
          checkName: build
          ref: master
          owner: name
          repo: repo
          intervalSeconds: 30

      - name: Build failure
        if: steps.wait-for-build-common.outputs.conclusion != 'success'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Build failed!')
```
