### ISSUE TITLE
GITHUB_TOKEN can be used

### ISSUE THREAD

**Issue by vavsab** [benc-uk/workflow-dispatch#41]
GH token can be used to trigger workflows. Please update the docs. It's a bit misleading. Just checked that this works
```yaml
- name: Invoke workflow without inputs
  uses: benc-uk/workflow-dispatch@v1
  with:
    workflow: CI
    token: ${{ secrets.GITHUB_TOKEN }}
```
