### ISSUE TITLE
Workflow does not have 'workflow_dispatch' trigger

### ISSUE THREAD

**Issue by EhsanHerai** [benc-uk/workflow-dispatch#46]
although, the workflow that I'm trying to trigger has the `workflow_dispatch` event.

``` yml
name: Release Publish
on:
  push:
    branches:
      - release-*
  workflow_dispatch:
  
  # rest of workflow ...
```

### Error
```
Workflow id is: 120726
Error: Workflow does not have 'workflow_dispatch' trigger
```
