### ISSUE TITLE
Regression in latest 1.2.1 version

### ISSUE THREAD

**Issue by alambike** [benc-uk/workflow-dispatch#50]
### Bug description

We see strange behavior in our workflows, after upgrading to the latest 1.2.1 version. 

After [this change](https://github.com/benc-uk/workflow-dispatch/commit/b8ac4001bdf17685419a1b65af6fa92fc9a3de0e#diff-3d2b59189eeedc2d428ddd632e97658fe310f587f7cb63b01f9b98ffc11c0197L573), now if the passed `ref` is an empty string, the action is not calculating the ref and the step fails.

Example:
```yaml
      - name: Dispatch my-workflow with workflow_dispatch
        if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
        uses: benc-uk/workflow-dispatch@b8ac4001bdf17685419a1b65af6fa92fc9a3de0e
        with:
          workflow: my-workflow
          ref: ${{ github.head_ref }}
```

In the case when a `workflow_dispatch` event triggers this workflow,  the `github.head_ref` is empty,  but now the action doesn't calculate the `github.ref`, as a `ref` input is passed, so the ref ends up as an empty string and the workflow execution fails with:
```
Error: No ref found for:
```

**Comment by benc-uk** [comment]
Hmmm interesting, maybe a good reason it was the way it was before!
I'll release a fix

**Comment by benc-uk** [comment]
Should be fixed in `master`, `v1`, `v1.2` and `v1.2.2`
Let me know if its not

**Comment by dpelengic** [comment]
Observing this issue in v1, after the update.

**Comment by bjoernw** [comment]
Still breaking even at `benc-uk/workflow-dispatch@a69ac85ea87587e76bb4f262eb868205dfcab8e8`

**Comment by dfar-io** [comment]
A workaround for the time being, adding `ref`:

```
- name: Trigger Deployment
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: YOUR_WORKFLOW
          ref: ${{ github.event.ref }}
          inputs: ANY_INPUTS_YOU_MIGHT_HAVE
```

**Comment by bjoernw** [comment]
Can confirm, workaround works. Going to leave this pinned to a git sha ;)
```
uses: benc-uk/workflow-dispatch@a69ac85ea87587e76bb4f262eb868205dfcab8e8
        with:
          workflow: my-workflow
          ref: ${{ github.event.ref }}
```
