### ISSUE TITLE
No Ref Found For on Version 1.2

### ISSUE THREAD

**Issue by whanata** [benc-uk/workflow-dispatch#51]
I'm currently getting an error `Error: No ref found for: ` ever since Version 1.2 was released.

```
- name: Trigger Transform User Profile
  uses: benc-uk/workflow-dispatch@v1
  with:
    workflow: transform-user-profile.yml
    inputs: '{ "environment": "all", "dry-run": "false", "initial-sync": "false" }'
```

I'm running this on a schedule once an hour and I currently don't have any reference.

I'll try to add the `master` branch to the `ref` and see if that works, but I believe there's an issue here.
This issue coincides with the Version 1.2 release.
