### ISSUE TITLE
Regression on token permissions

### ISSUE THREAD

**Issue by ddelange** [benc-uk/workflow-dispatch#52]
Hi 👋 

Just tried out your action (thanks 💥) and didn't get it to work ([logs](https://github.com/ddelange/actions-runner-controller-releases/actions/runs/3938563433/jobs/6737406003)):

`Error: Resource not accessible by integration`

The [yaml](https://github.com/ddelange/actions-runner-controller-releases/blob/c3c96bdb563ec06237db930ecb905aaef592b31c/.github/workflows/cron-release.yaml) is pretty straight-forward:
- default token
- same repo
```yaml
name: Trigger release-runners.yaml daily

on:
  schedule:
    - cron: "4 2 * * *"
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: release-runners.yaml
          inputs: '{"push_to_registries": true}'
```

Maybe something changed on gh side?

**Comment by jamiezieziula** [comment]
Fyi - I'm seeing the same behavior when trying to trigger a workflow within a single repository without passing a github token.

**Comment by jamiezieziula** [comment]
Actually, I was able to get this working by providing the following permissions to me action:
```
---
name: workflow

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  job:
    permissions:
      actions: write

.... abbreviated 

      - uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          ref: main
          workflow: workflowyaml
          token:  ${{ secrets.github_token }}
```
