### ISSUE TITLE
Error: Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by GeorgeXCV** [benc-uk/workflow-dispatch#55]
I keep getting this error, for some reason token isn't showing up as an input even though it is in the workflow file.

Workflow:
```
      - name: Trigger Cypress tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: front-end-pull-request.yml
          token: ${{ secrets.PAT }}
          repo: company/repo-name
          inputs: '{ "BRANCH_NAME": "${{ env.BRANCH_NAME }}", "TEST_URL": "${{ env.TEST_URL }}", "TEST_COMMIT": "${{ env.TEST_COMMIT }}" }'
```

Output:
```
Run benc-uk/workflow-dispatch@v1
  with:
    workflow: front-end-pull-request.yml
    repo: company/repo-name
    inputs: { "BRANCH_NAME": "", "TEST_URL": "", "TEST_COMMIT": "" }
```

`Error: Parameter token or opts.auth is required`
