### ISSUE TITLE
Version 121 is proposed by dependabot

### ISSUE THREAD

**Issue by r0manchak** [benc-uk/workflow-dispatch#56]
![image](https://user-images.githubusercontent.com/4974042/224027016-20b9c0ae-f3de-4c82-9443-d5683b3ed59e.png)

**Comment by chenrui333** [comment]
that might be more like a dependabot issue, I did not see any tag for 121 in the repo
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1580956/229401187-efdd7404-ab3d-459d-b138-d13f41bb4b32.png">

**Comment by giarc3** [comment]
Dependabot can find both tags and branches, and there is a branch here named `v121`, so I'm fairly sure that's the source of its confusion. It would be nice for this to be resolved as all the Dependabot PRs are noisy/wrong to merge

**Comment by aidan-mundy** [comment]
Also running into this issue. Just want to confirm that the cause is the branch, and this is expected behavior from Dependabot, since many actions use a `vXXX` syntax instead of the more semver-like `vXX.YY.XX` (or in this repo's case, `vXX`, `vXX.YY`, and `vXX.YY.ZZ`, with trailing zeroed segments dropped :upside_down_face:)

**Comment by mara004** [comment]
I think adding the following ignore rule should help:
```yml
  - package-ecosystem: "github-actions"
    # ...
    ignore:
      - dependency-name: "benc-uk/workflow-dispatch"
        versions: ["121"]  # presumably an upstream accident
```
Related incident: https://github.com/pypdfium2-team/pypdfium2/pull/297
