### ISSUE TITLE
Not found with all valid parameters

### ISSUE THREAD

**Issue by hiteshbal91dp** [benc-uk/workflow-dispatch#60]
Hi Team, 

Following is my configuration which has all the required params but still getting not found with following error.

```
- name: Trigger Automation Workflow
  uses: benc-uk/workflow-dispatch@v1
  with:
    token: ${{ secrets.PAT_GITHUB }}
    workflow: 'automation.yml'
    ref: 'feat/automation-cicd'
    repo: ${{ github.repository_owner }}/${{ vars.AUTOMATION_REPOSITORY_NAME }}
    inputs: '{"service": "config","env": "${{ env.QA_ENV }}"}'
```

Following is output that I am getting,    
```
Unable to find workflow 'automation.yml' in ORG/REPO 😥
```

Anything I am missing here?, I have file named "automation.yml" in branch "feat/automation-cicd" in directory "/.github/workflows" 
 in my repo but still it is giving 404.
