### ISSUE TITLE
Workflow does not have workflow_dispatch trigger.

### ISSUE THREAD

**Issue by aangelinsf** [benc-uk/workflow-dispatch#65]
With the following invocation:

```
      - name: Invoke QA workflow.
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          workflow: just-run-workflow.yml
```

And the recipient workflow of:
```
name: Display message.
on:
  workflow_dispatch:
jobs:
  display-message:
    runs-on: ubuntu-latest
    steps:
      - name: Show echo.
        run: |
          echo "This ran."
```

I'm getting this error:

```
Run benc-uk/workflow-dispatch@v1
  
🏃 Workflow Dispatch Action v1.2.1
🔎 Found workflow, id: [8](https://github.com/aangelinsf/dxpr_builder/actions/runs/7342704455/job/19992280983#step:6:8)05[8](https://github.com/aangelinsf/dxpr_builder/actions/runs/7342704455/job/19992280983#step:6:9)7277, name: Display message., path: .github/workflows/just-run-workflow.yml
🚀 Calling GitHub API to dispatch workflow...
Error: Workflow does not have 'workflow_dispatch' trigger
```

However, the `workflow_dispatch:` is there. 

Any suggestion as to what's going wrong?
